### ISSUE TITLE
two locos occupied the same coordinates

### ISSUE THREAD

**Issue by Saumya-Mishra9129** [sugarlabs/locosugar#16]
During press of lowercase keys as well as upperkeys, two locos occupied the same coordinates, so it was difficult to read the letters.
Steps involve - starting game from level 1 , reach to level -4, press lower keys -  you may not see error in one try, try from start again in that case. Follow same steps for level-5.
For reference look at pr #14

**Comment by quozl** [comment]
Thanks.  We use issues as a signal that we don't plan to fix something, so I've looked into this issue more deeply.

* as originally written, the random positioning in `new_game` and `_quad_to_xy` does risk collision without detection,
* for the initial games this is easy handled by the child,
* for the letter games the solution is not obvious,
* 2ca12801b95c4c89b308dee41b679281e7821d6a added a feature to let the child drag to remove overlaps,
* [How to use LocoSugar](https://help.sugarlabs.org/locosugar.html) does not mention this feature,
* 1f9c2acf2e3f8446d8685183fba3028250b862d4 help with overlaps, by hiding the Loco after it is identified by the child.

So it would seem this is adequate, and my review comments in the pull request stem from ignorance of the activity features.
