### ISSUE TITLE
Ghost loco is stuck on screen

### ISSUE THREAD

**Issue by JuiP** [sugarlabs/locosugar#17]
![Ghost_loco](https://user-images.githubusercontent.com/46154968/85196633-37bdae00-b2f9-11ea-86ef-b2d3acbe4112.png)
First noticed by @quozl in #14 ; 
@JuiP and @Saumya-Mishra9129 confirmed.

**Comment by Saumya-Mishra9129** [comment]
> First noticed by @quozl in #14 ;
> @JuiP and @Saumya-Mishra9129 confirmed

Also , It is not necessary that it will be visible in first round of play. If you couldn't find first time, Try more subsequent rounds.

**Comment by JuiP** [comment]
In #14,
@Saumya-Mishra9129 confirmed that this cannot be reproduced anymore. ([comment](https://github.com/sugarlabs/locosugar/pull/14#issuecomment-655356371))

@quozl confirmed that this cannot be reproduced anymore. ([comment](https://github.com/sugarlabs/locosugar/pull/14#issuecomment-655922239))

@JuiP confirmed that this cannot be reproduced anymore. ([comment](https://github.com/sugarlabs/locosugar/pull/14#issuecomment-655963178))

So closing this issue.
