### ISSUE TITLE
Exit button disappearing on start

### ISSUE THREAD

**Issue by Ark74** [sugarlabs/locosugar#20]
There seems to be an issue (possibly a regression) on the LocoSugar activity.

* **Package version:** 12

Once it's open the exit fullscreen mode button disappears. leaving no possible way to exit full screen.
Only recently I have found that Ctrl +Q, exits the activity.

It would be nice to have the exit fullscreen button active during the activity, or maybe add "Use Ctrl + Q to exit" on the panel shown at start.

Best regards

**Comment by chimosky** [comment]
There was an ongoing discussion about this in #12 which also links to #14. You can take a look at those, closing this as it's a duplicate.

**Comment by Ark74** [comment]
F3 seems to take you to main menu, this could be used as a workaround.

Regards
